### ISSUE TITLE
What's the different ethstats-backend with ethstats-server?

### ISSUE THREAD

**Issue by Aldiwildan77** [maticnetwork/ethstats-backend#9]
Sorry for asking this, I'm interested in this project. But I get something similar but didn't know about the difference between ethstats-backend and ethstats-server.

**Comment by ferranbt** [comment]
Hi, ethstats-server is a combination of three things: a frontend, a websocket ingress collector and an in memory database to aggregate the data. Though the data we get from the client nodes is quite rich and insightful, this monolithic arquitecture makes it hard to analyze it in detail.

This project is an implementation of the websocket collector which stores all the incoming data in a PostgreSQL database, it does not do any frontend. Besides, it can proxy the data to an ethstats-server.

**Comment by Aldiwildan77** [comment]
Thanks fyi, okay understand with that. I'll close this issue.
